fix(fastapi): Upgrade FastAPI and switch to Strawberry (#945)
* Upgrade fastapi to 0.65.0

Tests are passing.

* Migrate mutation for recommendation preferences

* Add listTopics query

* Extend User with recommendationPreferences

* Add recommendationPreferenceTopics

* Migrate get_field_argument to strawberry

* Add setupMomentSlate

* Initial migration of getSlateLineup

* Move mutation class to graphql_router

* Fix test_get_slate_lineup by disabling clear_caches()

* Fix candidate sets test

* Add pytest configuration conftest.py

* All tests pass

* Export Strawberry schema to Apollo

* Fix strawberry command not found

* Switch to docker compose run

* Fix docker compose -> docker-compose

* Fix docker build

* fix docker login error

Cannot perform an interactive login from a non TTY device

* Try to switch to a machine image

Traceback (most recent call last):
  File urllib3/connectionpool.py, line 677, in urlopen
  File urllib3/connectionpool.py, line 392, in _make_request
  File http/client.py, line 1277, in request
  File http/client.py, line 1323, in _send_request
  File http/client.py, line 1272, in endheaders
  File http/client.py, line 1032, in _send_output
  File http/client.py, line 972, in send
  File docker/transport/unixconn.py, line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

* fix missing context for apollo

* Fix circleci syntax error

* fix permission error exporting schema.graphql

* Fix Cannot query field 'item_id'

* Fix apollo errors

- CorpusItem cannot redeclare topic because it's not shareable by curated-corpus
- Recommendation.item needs to be shareable for curation-tools to extend it

* Upgrade Apollo Rover from 0.1.0 to 0.8.1

* Add getSlate query

* Fix SATISFIABILITY_ERROR with curation-tools

* Fix description changes in graphql schema

* Fix description and type changes

* Add count to CorpusSlateLineup.slates

* Schema matches exist schema

* Install uvicorn with standard extras

This is the recommended way to install uvicorn in a production environment.
Without the 'standard' extras it uses a pure Python event loop for debugging purposes.

* Fix setupMomentSlate test errors

* Remove unused pipenv dependencies

These packages are already required by packages we use directly.
They were previously added to freeze the version in Pipfile.

* Fix schema typos

This brings it in sync with what exists on the main branch.

* Move GraphQL item class and cleanup cache test