Try to switch to a machine image
Traceback (most recent call last):
  File urllib3/connectionpool.py, line 677, in urlopen
  File urllib3/connectionpool.py, line 392, in _make_request
  File http/client.py, line 1277, in request
  File http/client.py, line 1323, in _send_request
  File http/client.py, line 1272, in endheaders
  File http/client.py, line 1032, in _send_output
  File http/client.py, line 972, in send
  File docker/transport/unixconn.py, line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory