feat(Telemetry): Switch to OpenTelemetry [DIS-83] (#1009)
* feat(Telemetry): Install OpenTelemetry

* chore(Telemetry): Disable X-Ray segments and exporter

* feat(Telemetry): Open Telemetry exports to X-Ray

* feat(Telemetry): Switch daemon to OTEL

* fix(Telemetry): Incorrect daemon address

* fix(Telemetry): Incorrect daemon address

* feat(Telemetry): Add Strawberry instrumentation

* feat(Telemetry): Instrument aiobotocore and aiohttp

* feat(Telemetry): Add FeatureStore extension

* feat(Telemetry): More meaningful segment names

* feat(Telemetry): Add custom span to SlateProvider

* chore(Telemetry): Remove superfluous telemetry decorators

* feat(Telemetry): Add DynamoDB extension

* feat(Telemetry): Enable contrainer metrics

* chore(Telemetry): Stop disabling X-Ray in tests

* feat(Load test): Add homeSlateLineup dev test

* chore(Telemetry): Delete unused config

* chore(Telemetry): Add link to botocore instrumentation

* chore(Telemetry): Remove unused HTTP exporter

* feat(Telemetry): Add ECS resource attributes

* feat(Telemetry): Add request headers

* fix(Telemetry): Remove commented code

* chore(Telemetry): Lock packages that are in beta

These packages are expected to have breaking changes, so we want to lock them in place for now.

* fix(Telemetry): Pipfile.lock is out of date

* feat(Telemtry): Provide option to disable telemetry

* fix(Telemetry): Invalid version v2.3 for federation

Error: Invalid version v2.3 for the federation feature in @link direction on schema