Async dynamodb (#92)
* Made DynamoDB queries asynchronous

There are dependency conflicts between metaflow and aioboto3. We shouldn't be mixing dependencies for the lambda, jobs, and application.
I think the solution might be to put a pipenv file in /jobs and /aws_lambda. Alternatively we could create separate repos.

* Separate Pipenvs

* WIP tests

* Fixed GIT_SHA not being set

ARG needs to be declared after the 'FROM' statement to be available afterwards.
https://benkyriakou.com/posts/docker-args-empty

* Run Lambda tests in separate environment

* Fixed circle config syntax error

* WIP

* WIP refactor tests

* Rewrite aws_lambda tests to pytest

* WIP tests

* Limited aws lambda dependencies

* Remove localstack from CircleCI test configs

* CircleCI activates pipenv shell based on parameter

* Run tests in pipenv directory

* Change test directory to relative path to pipenv

* Restore pipenv run

* Don't set local Docker env variables in CircleCI

This tells moto to connect to localstack:
EndpointConnectionError: Could not connect to the endpoint URL: http://localstack:4566/

* Add caching to CircleCI tests

* Set WORKON_HOME env variable for all test steps

* Fix pipenv location for caching

* App tests pass locally

* Separate Lambda and app CircleCI configs

* Make metaflow_check pipenv run in jobs/

* Fix lambda test after rename

* Fix merge error that broke app test

* Fix build paths

* Use pipenv shell instead of pipenv run

* Move Metaflow flows to jobs/

* Retry build

* Fix check_metaflow